---
- name: "Test if netdata_cloud_enable is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_cloud_enable is defined
      - netdata_cloud_enable is boolean
    quiet: true

- name: "Test if netdata_cloud_claim_url is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_cloud_claim_url is defined
      - netdata_cloud_claim_url is string
    quiet: true
  when: netdata_cloud_enable

- name: "Test if netdata_cloud_claim_token is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_cloud_claim_token is defined
      - netdata_cloud_claim_token is string
    quiet: true
  when: netdata_cloud_enable

- name: "Test if netdata_cloud_force_claim is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_cloud_force_claim is defined
      - netdata_cloud_force_claim is boolean
    quiet: true
  when: netdata_cloud_enable

- name: "Test if netdata_agent_channel is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_agent_channel is defined
      - netdata_agent_channel is string
      - netdata_agent_channel in ['stable', 'edge']
    quiet: true

- name: "Test if netdata_agent_state is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_agent_state is defined
      - netdata_agent_state is string
      - netdata_agent_state in ['present', 'absent']
    quiet: true

- name: "Test if netdata_agent_conf_template is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_agent_conf_template is defined
      - netdata_agent_conf_template is string
    quiet: true

- name: "Test if netdata_agent_web_enabled is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_agent_web_enabled is defined
      - netdata_agent_web_enabled is boolean
    quiet: true

- name: "Test if netdata_agent_web_port is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_agent_web_port is defined
      - netdata_agent_web_port is integer
    quiet: true
  when: netdata_agent_web_enabled

- name: "Test if netdata_disable_email_notifications is set correctly"
  ansible.builtin.assert:
    that:
      - netdata_disable_email_notifications is defined
      - netdata_disable_email_notifications is boolean
    quiet: true
